### ISSUE TITLE
网络训练

### ISSUE THREAD

**Issue by xuhewei98** [C-Fun/Local-Patch-Network-with-Global-Attention#1]
作者您好，请问你们的epoch设置是多大呢？看您的代码里设置为20，但是跑出来的效果似乎很差

**Comment by C-Fun** [comment]
您好，我是使用的第14个epoch的结果，您试试设置成14看一下，如果效果还是不好请再与我联系。


------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "C-Fun/Local-Patch-Network-with-Global-Attention"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2022年5月26日(星期四) 下午5:00
***@***.***&gt;;
***@***.***&gt;;
主题:&nbsp;[C-Fun/Local-Patch-Network-with-Global-Attention] 网络训练 (Issue #1)





 
作者您好，请问你们的epoch设置是多大呢？看您的代码里设置为20，但是跑出来的效果似乎很差

**Comment by xuhewei98** [comment]
您好，请问SIRST这个数据集您也是跑14个epoch吗？我这边14个epoch跑出来的效果很差







------------------&nbsp;原始邮件&nbsp;------------------
发件人: ***@***.***&gt;; 
发送时间: 2022年5月26日(星期四) 下午5:07
收件人: ***@***.***&gt;; 
抄送: ***@***.***&gt;; ***@***.***&gt;; 
主题: Re: [C-Fun/Local-Patch-Network-with-Global-Attention] 网络训练 (Issue #1)





 您好，我是使用的第14个epoch的结果，您试试设置成14看一下，如果效果还是不好请再与我联系。 
 
 
 ------------------&amp;nbsp;原始邮件&amp;nbsp;------------------ 
 发件人:                                                                                                                        "C-Fun/Local-Patch-Network-with-Global-Attention"                                                                                    ***@***.***&amp;gt;; 
 发送时间:&amp;nbsp;2022年5月26日(星期四) 下午5:00 
 ***@***.***&amp;gt;; 
 ***@***.***&amp;gt;; 
 主题:&amp;nbsp;[C-Fun/Local-Patch-Network-with-Global-Attention] 网络训练 (Issue #1) 
 
 
 
 
 
   
 作者您好，请问你们的epoch设置是多大呢？看您的代码里设置为20，但是跑出来的效果似乎很差

**Comment by xuhewei98** [comment]
或者是否能给出两个公开数据集上训练的预训练模型呢

**Comment by xuhewei98** [comment]
作者您好，我又重新在SIRST数据集上训练了1500个epoch，但是效果依旧不是很好，请问方便告知您在这个数据集上的具体参数设置吗？

**Comment by C-Fun** [comment]
您好，SIRST数据集的epoch不需要设这么多，导致过拟合了。之前复现的时候我只在MFIRST上跑了，等我在SIRST上跑一下把两个数据集的超参设置和预训练模型一并放上来。

**Comment by C-Fun** [comment]
您好，训练超参和预训练文件已经更新，请参考最新版本的代码。
